server:
  port: 8084

spring:
  application:
    name: collaboration-service

springdoc:
  api-docs:
    path: /sessions/v3/api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
